### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by shaicoleman** [moiristo/deep_cloneable#106]
Currently the gemspec has the following line:

`s.add_dependency(%q<activerecord>.freeze, ["< 6", ">= 3.1.0"])`

**Comment by moiristo** [comment]
Hi,

Will look into it, probably this weekend. Do you know if it already works as is in rails 6?

**Comment by shaicoleman** [comment]
Didn't have a chance to check yet

**Comment by moiristo** [comment]
Alright, thanks!

**Comment by moiristo** [comment]
Will be fixed in v3 (now in master)
