### ISSUE TITLE
Multiple attachments for a nested association

### ISSUE THREAD

**Issue by vitobotta** [moiristo/deep_cloneable#115]
Hi! I have a model with some nested associations, and the last association can have multiple attachments uploaded with ActiveStorage. How do I adapt the  snippet in the README to this case? The example seems to be for a parent model with a single attachment, while I have multiple attachments with a nested association/model. 

Thanks in advance!

**Comment by moiristo** [comment]
I'm sorry, I don't know as I don't use ActiveStorage yet :) Please let me know if you find out.

**Comment by letiesperon** [comment]
Has this been solved? I have the same question for carrierwave

**Comment by moiristo** [comment]
No, I haven't heard back. Looking at the [docs](https://edgeapi.rubyonrails.org/classes/ActiveStorage/Attached/Model.html#method-i-has_many_attached), I can see that multiple attachments are basically attachments via has-many-through, so you might be able to do the same as for the singular version by iterating over the records in the association?

**Comment by moiristo** [comment]
Oh wait, you were referring to carrierwave :) Seems you need to associate an array of file paths in that case, see: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-%22Upload%22-from-a-local-file

**Comment by Roko131** [comment]
The current active storage example in the readme didn't work for me- `rails 5.2`.
It uses `ActiveStorage::Downloader` but I received `NameError: uninitialized constant ActiveStorage::Downloader`

Here's a both `has_one_attached` and `has_many_attached` snippets for `rails 5.2`

```ruby
# Rails 5.2, has_one_attached example
pirate.deep_clone include: :parrot do |original, kopy|
  if kopy.is_a?(Pirate) && original.avatar.attached?
    attachment = original.avatar
    kopy.avatar.attach \
      :io           => StringIO.new(attachment.download),
      :filename     => attachment.filename,
      :content_type => attachment.content_type
  end
end

# Rails 5.2, has_many_attached example
pirate.deep_clone include: :parrot do |original, kopy|
  if kopy.is_a?(Pirate) && original.crew_members_images.attached?
    original.crew_members_images.each do |attachment|
      kopy.crew_members_images.attach \
        :io           => StringIO.new(attachment.download),
        :filename     => attachment.filename,
        :content_type => attachment.content_type
    end
  end
end
```

**Comment by moiristo** [comment]
Thanks for this, I've updated the readme!

**Comment by febincloudyuga** [comment]
I'm stuck with this problem too, where I have a multiple attachment for a nested association. Any inputs on how to go about it would help.

I have this association -
* A building has many floors
* A floor has many rooms
* A room has many beds

Without ActiveStorage, I'm able to make a deep clone as below -
`building.deep_clone include: [floors: [rooms: [:beds]]]`

I have an ActiveStorage dependency of `bed has_many_attached :sheets`
The Readme describes the usage of ActiveStorage for parent model, but not for the nested models.

Could you please shed some light on how to go about it?

Thanks.

**Comment by moiristo** [comment]
Hi,

As the readme states, a passed block will be evaluated for every copy created. That's why it's needed to check the class of the copy before doing stuff. So, in your case, you just need to check that the copied object is in fact a `Bed`.

```ruby
building.deep_clone include: [floors: [rooms: [:beds]]] do |original, kopy|
  if kopy.is_a?(Bed) && original.sheets.attached?
     # ActiveStorage copy strategy for sheets
  end
end
```

**Comment by febincloudyuga** [comment]
> Hi,
> 
> As the readme states, a passed block will be evaluated for every copy created. That's why it's needed to check the class of the copy before doing stuff. So, in your case, you just need to check that the copied object is in fact a `Bed`.
> 
> ```ruby
> building.deep_clone include: { floors: { rooms: :beds } } do |original, kopy|
>   if kopy.is_a?(Bed) && original.sheets.attached?
>      # ActiveStorage copy strategy for sheets
>   end
> end
> ```

Thank you very much. I was able to get it to work.
Appreciate the quick response :)
