### ISSUE TITLE
include:do loop also modified the includes

### ISSUE THREAD

**Issue by aximuseng** [moiristo/deep_cloneable#123]
Here is my deep clone code:

    @duplicate = @budget.deep_clone include: :budget_items, except: [:slug, :comments_count, :uploads_count ] do |original, duplicate|
      duplicate.name = "#{original.name} Copy"
    end

The expected action is that the `budget.name` has Copy appended.  The issue is that my `budget_items` model also has a name attribute and when deep cloned those associated records get modified also.

**Comment by moiristo** [comment]
Hello,

This is documented behavior, please see the note in the [Optional Block section](https://github.com/moiristo/deep_cloneable#optional-block).
