### ISSUE TITLE
'Add support for conditionals in array inclusions' isnot in 2.1.1

### ISSUE THREAD

**Issue by hw676018683** [moiristo/deep_cloneable#53]
The usage of the following isnot in 2.1.1, please add a new version
```ruby
ship.deep_clone include: [
  pirates: [ :treasures, :mateys, if: lambda {|pirate| pirate.name == 'Jack Sparrow' } ]
]
```
this maybe mislead others, sush as me

**Comment by moiristo** [comment]
Whoops, you're right! I built that back in april in my free time, but I never got any feedback for it, that's why I didn't release it. Have you tried it using the git master and does it work as it should?

**Comment by hw676018683** [comment]
it is not what i expected. I looked at the source code, i need it no more, so i donot test it.
I need one that conditionally selects associations according to parent association, but i did not find the one.

**Comment by moiristo** [comment]
Added in 2.2.0.
