### ISSUE TITLE
Support Rails 5 (specifically Active Record v5.0)

### ISSUE THREAD

**Issue by djsegal** [moiristo/deep_cloneable#59]
Unable to get `Gemfile.lock` to compile because of version restrictions

**Comment by moiristo** [comment]
Hi! Thanks, I will look into it shortly. I need to update travis.yml to include rails 5 before I can merge this in.

**Comment by moiristo** [comment]
I've updated the gem to 2.2.1. The Travis build including Rails 5 works now.
