### ISSUE TITLE
Clarification in README regarding uploaders

### ISSUE THREAD

**Issue by svensson-david** [moiristo/deep_cloneable#61]
Hello!
I had some issues with cloning models with mounted uploaders, in my case Carrierwave.
Best solution i found was using a block when cloning and setting the attributes manually to get the files to copy together with the other data.

I think it could be good to add a note in the README regarding this to make the process smoother for others.

**Comment by moiristo** [comment]
PR? 😉

**Comment by svensson-david** [comment]
Sure thing, I'll sort it out during the beginning of the week

**Comment by moiristo** [comment]
Thanks!

**Comment by svensson-david** [comment]
Sorry for the delay, added the PR now

**Comment by moiristo** [comment]
Thanks! 👍
