### ISSUE TITLE
Can't clone just an association without explicitly excluding all parent attributes

### ISSUE THREAD

**Issue by brahnema** [moiristo/deep_cloneable#72]
It would be nice to be able to clone only an association while excluding all parent attributes like so:
```
pirate.deep_clone only: :treasures
```

Obviously, this can be done by including the association and then explicitly excluding the parent attributes:
```
pirate.deep_clone include: :treasures, except: Pirate.column_names
```
but I expected `only` to work properly for this.

**Comment by moiristo** [comment]
`:only` is the inverse of `:except`, it's not meant for specifying inclusions. This would do the same, I guess:

```ruby
pirate.deep_clone only: [], include: :treasures
```

**Comment by brahnema** [comment]
That works. Closing.
