### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by dsounded** [moiristo/deep_cloneable#76]
I have troubles with Rails 5 and postgres:

`foreign key field is not a number and some other fields are invalid`, any ballpark date for Rails 5 compatibility ?

**Comment by moiristo** [comment]
The test suite is being run on TravisCI using rails 5.0.0.1 and passes. Which version are you exactly talking about?

**Comment by dsounded** [comment]
`5.0.0.1` same, but my locals specs pass on Rails 4.2 and don't pass on `5`

**Comment by moiristo** [comment]
It might have to do with the new [rails defaults for belongs_to](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#active-record-belongs-to-required-by-default-option). But I'm not sure. Do you think you can come up with a failing test case?

**Comment by dsounded** [comment]
@moiristo 
From what I see, there is another validation in Rails 4/5:

I've tried to debug here
`deep_cloneable-2.2.2/lib/deep_cloneable.rb:88`

`kopy.associations.map(&:association_field)` (where associations is just a has many relation)
`[nil, nil, nil, nil]`
same in Rails 4 and 5

But `kopy.associations.map(&:valid?)`
Rails 4:
`[true, true, true, true]`
Rails 5:
`[false, false, false, false]`

That's why it says `not a number`, 'cause it's `nil`

**Comment by dsounded** [comment]
adding `config.active_record.belongs_to_required_by_default = false` into config didn't solve the problem

**Comment by moiristo** [comment]
So it tells you that the associated objects are not valid. What are the errors? Can you do something like: `kopy.associations.map{|record| record.valid?; record.errors.full_messages.join(',') }` and see what the validation errors are?

**Comment by dsounded** [comment]
`@details={:association__id=>[{:error=>:not_a_number, :value=>nil}]},`
`@messages={:association_id=>["is not a number"]}`

**Comment by moiristo** [comment]
Ok, so `kopy.associations` points to a certain list of objects that contain a `belongs_to` somewhere that is stored in `association_id`. Does it work when you make that `belongs_to` optional?

**Comment by dsounded** [comment]
Added `optional: true` to `belongs_to` relation, it doesn't work as well,
btw I have `belongs_to` with params `class_name` and `foreign_key` if it matters...

**Comment by moiristo** [comment]
Hmm, it might be that rails5 handles things differently when `nil` is explicitly being passed to an association. Just a hunch.. I'll try to find out if I can reproduce the error in the test suite.

**Comment by dsounded** [comment]
Doing the same on new rails 5 project

**Comment by moiristo** [comment]
👍  please let me know when you know more!

**Comment by dsounded** [comment]
After deeper digging into the problem I've seen it's my custom validation fails, sorry for that...

thanks for the gem, btw

**Comment by moiristo** [comment]
Ok, thanks for the feedback!
