### ISSUE TITLE
STI associations

### ISSUE THREAD

**Issue by mrsweaters** [moiristo/deep_cloneable#78]
How would this work with STI associations that are not available on the parent?
```ruby
class Road
end

class Expressway < Road
end

class Highway < Road
  has_many :bridges
end

@new_highway = @road.deep_clone include: :bridges
```

This is failing for any non-highway roads.
```ruby
ActiveRecord::Base::DeepCloneable::AssociationNotFoundException: Expressway#bridges
```

**Comment by moiristo** [comment]
Hmm, yeah that's not possible yet. Maybe there should be an option like `:skip_missing_associations` or something.. I'll try to come up with something tonight, should be easy to implement.

**Comment by mrsweaters** [comment]
@moiristo Thanks for looking into it!

**Comment by moiristo** [comment]
I just added support for the `skip_missing_associations` option in master. Could you check if it suits your needs? If everything is ok, I'll make a new release.

**Comment by mrsweaters** [comment]
@moiristo Thanks! I'll take a look at this and let you know. I really appreciate it!

**Comment by mrsweaters** [comment]
This worked great!
