### ISSUE TITLE
how to use deep_clone in has_ancestry relation

### ISSUE THREAD

**Issue by rajeev-khangar** [moiristo/deep_cloneable#80]
please look into this.
https://github.com/stefankroes/ancestry

I would like to keep ancestry data as well when I am going to deep clone and ancestry column value should  
be changed during deep cloning.

Please suggest me what should i do.

**Comment by moiristo** [comment]
I don't think that's possible, as the hierarchy is not defined via an association. However, I think you could work around it by specifying the optional block. What I would do is something like the following:

* Specify a dictionary manually, containing your tree nodes with a reference to a copy of that node (see docs)
* Define an accessor on each node which will contain the copy instance of its parent node
* Set the accessor by passing a block to `deep_clone`, which sets the accessor
* Rebuild the tree after copying by setting the ancestry parent of each node and saving. You should start at the root node for this and work your way down.

I hope you can find a solution for this. It would be nice if you could share it with us when you do ;)
