### ISSUE TITLE
Block processing isn't in an obvious place

### ISSUE THREAD

**Issue by davefp** [moiristo/deep_cloneable#81]
From the README:
> Pass a block to deep_clone to modify a duped object after duplication
My assumption after reading the above was that my block would get executed right before the copy was returned.

In particular, properties excluded with the `except` parameter would be gone and any value I wrote to those fields would be included in the copy.

This isn't the case, as exclusion happens _after_ the block is invoked.

For now I suggest adding something like the following to the docs:

`Note: The block is invoked before properties are excluded`

In a future version, I think invoking the block after all other processing would be more valuable.

**Comment by davefp** [comment]
I'm happy to submit a PR for the documentation change, BTW.

**Comment by moiristo** [comment]
Hi, thanks for your feedback! I agree that it's in the wrong place. I added the note you specified to the docs.

**Comment by davefp** [comment]
Brill, thanks!
