### ISSUE TITLE
Rails 5.2

### ISSUE THREAD

**Issue by brian-kephart** [moiristo/deep_cloneable#92]
My installation of this gem downgraded when I updated from Rails 5.2.0rc2 to 5.2.0. The gemspec needs to be updated.

**Comment by moiristo** [comment]
Hello! Thanks for your contribution! I just wondered: did you drop support for ruby < 2.2 and rails 3.1 in your PR because they're EOL?

**Comment by moiristo** [comment]
Seen your new PR, thanks for that! I think it's not bad to eventually clean up the EOL rubies and drop support for 3.1, we can also use the new hash syntax then and drop the `protected initialize_dup` line in the code. For now, I'll merge your last PR and make a patch release when everything is ok!

**Comment by moiristo** [comment]
Fixed in 2.3.2.
